spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/your_database_name
    url: jdbc:mysql://localhost/whistleblower_db?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect